#!/usr/bin/env bash

option="$1"

venv_root=".venv"

clean () {

    find . -exec touch {} +
}

install () {

    echo "installing os package dependencies ..."
    sudo apt install python3-tk
    echo "... installed os package dependencies"

    echo "creating & activating virtual environment @ $venv_root ..."
    python3 -m venv $venv_root
    source $venv_root/bin/activate
    echo "... created & activated virtual environment @ $venv_root"

    echo "installing & updating pip ..."
    python3 -m pip install --upgrade pip
    python3 -m pip install pip-tools
    echo "... installed & updated pip"

    echo "compiling requirements.txt from requirements.in ..."
    pip-compile requirements.in
    echo "... compiled requirements.txt from requirements.in"

    echo "installing python modules from requirements.txt to $venv_root ..."
    pip-sync requirements.txt
    echo "... installed python modules from requirements.txt to $venv_root"

    deactivate
}

test () {

    # rm -rf .pytest_cache
    # rm -rf perceptron/__pycache__
    # rm -rf tests/__pycache__

    source $venv_root/bin/activate

    x=1
    while [ $x == 1 ]
    do
        python3 -m pytest --verbose tests/test_networks.py

        echo "repeat? yY/nN"
        read repeat     

        if [ "$repeat" != "y" ]; then
            x=0
        fi
    done

    deactivate
}

usage () {
    echo "usage: invoke [ clean | install | test]"
}

case "$option" in

    clean)
        clean
    ;;

    install)
        install
    ;;

    test)
        test
    ;;

    *)
        usage
    ;;
esac