#!/usr/bin/env bash

option="$1"

venv_root=".venv"
os_packages="python3-tk"

clean () {

    sudo rm -rf .pytest_cache
    sudo rm -rf perceptron/__pycache__
    sudo rm -rf perceptron/demos/__pycache__
    sudo rm -rf tests/__pycache__
}

install_os_packages () {

    echo "installing os packages ..."
    sudo apt install $os_packages
    echo "... installed os packages"
}

create_venv () {

    echo "creating virtual environment @ $venv_root ..."
    python3 -m venv $venv_root
    echo "... created virtual environment @ $venv_root"
}

activate_venv () {

    source $venv_root/bin/activate
    echo "$(python --version) venv @ $(which python)"
}

deactivate_venv () {

    deactivate
}

install_and_upgrade_pip () {

    python -m pip install --upgrade pip
    echo "$(python -m pip --version)"
}

install_python_modules () {

    echo "installing python modules ..."
    python -m pip install -r requirements.txt
    echo "... installed python modules"
}


setup () {

    install_os_packages
    create_venv
    activate_venv
    install_and_upgrade_pip
    install_python_modules
    deactivate_venv
}

test () {

    source $venv_root/bin/activate
    python3 -m pytest --verbose tests/
    deactivate
}

demo () {

    source $venv_root/bin/activate
    python3 -m perceptron.demos.demo
    deactivate
}

demo-cardinality-sweep () {

    source $venv_root/bin/activate
    python3 -m perceptron.demos.demo_cardinality_sweep
    deactivate
}

demo-unreachable-class () {

    source $venv_root/bin/activate
    python3 -m perceptron.demos.demo_unreachable_class
    deactivate
}

usage () {
    echo "usage: invoke [ clean | install | test | demo | demo-cardinality-sweep | demo-unreachable-class ]"
}

case "$option" in

    clean)
        clean
    ;;

    setup)
        setup
    ;;

    test)
        clean
        test
    ;;

    demo)
        demo
    ;;

    demo-cardinality-sweep)
        demo-cardinality-sweep
    ;;

    demo-unreachable-class)
        demo-unreachable-class
    ;;

    *)
        usage
    ;;
esac
