#!/usr/bin/env bash

sudo apt install python3.10-venv

python3 -m venv .env
source .env/bin/activate

python3 -m pip install --upgrade pip
python3 -m pip install pip-tools

pip-compile requirements.in
pip-sync requirements.txt
