#!/usr/bin/env bash

python3 -m venv .env
source .env/bin/activate

python3 -m pip install --upgrade pip
python3 -m pip install pip-tools

pip-compile requirements.in
pip-sync requirements.txt

python3 -m pytest --verbose tests/test_networks.py

