#!/usr/bin/env bash

rm -rf .pytest_cache
rm -rf perceptron/__pycache__
rm -rf tests/__pycache__

source .env/bin/activate

for i in $(seq 1 1);
do
    python3 -m pytest --verbose tests/test_networks.py
done

